import CryptoKit
import Foundation
import TranscodeKit

/// User-adjustable pieces of the Digital Cinema Naming Convention string
/// (and the CPL ContentKind derived from it).
public struct DCNCOptions: Sendable, Equatable {
    public enum Kind: String, CaseIterable, Sendable {
        case auto = "Auto"
        case feature = "FTR"
        case short = "SHR"
        case trailer = "TLR"
        case test = "TST"

        /// CPL ContentKind value (SMPTE 429-7 vocabulary).
        var contentKind: String {
            switch self {
            case .feature: return "feature"
            case .short: return "short"
            case .trailer: return "trailer"
            case .test: return "test"
            case .auto: return "feature"
            }
        }
    }

    public var kind: Kind
    /// ISO 639 audio language code, "XX" = none/unknown.
    public var audioLanguage: String
    /// Subtitle language code, "XX" = no subtitles.
    public var subtitleLanguage: String
    /// Facility/creator code (2–4 letters).
    public var facility: String

    public init(kind: Kind = .auto, audioLanguage: String = "XX",
                subtitleLanguage: String = "XX", facility: String = "PRC") {
        self.kind = kind
        self.audioLanguage = audioLanguage
        self.subtitleLanguage = subtitleLanguage
        self.facility = facility
    }

    /// Resolves `.auto` by duration (under 40 min at 24 fps → short).
    public func resolvedKind(frameCount: Int) -> Kind {
        guard kind == .auto else { return kind }
        return frameCount < 40 * 60 * 24 ? .short : .feature
    }

    static func sanitizeCode(_ code: String, fallback: String, maxLength: Int) -> String {
        let cleaned = code.uppercased().filter { $0.isLetter || $0.isNumber }
        return cleaned.isEmpty ? fallback : String(cleaned.prefix(maxLength))
    }
}

/// SMPTE ST 429 packaging: CPL (429-7), PKL (429-8), ASSETMAP/VOLINDEX (429-9).
/// XML is generated by templating — the formats are small, fixed, and golden-file tested.
public enum DCPPackage {
    public static let issuer = "kennethbeckerdite"
    public static let creator = "ProRes Compressor 0.1.0"

    public struct Input {
        public let folderURL: URL
        public let contentTitle: String
        /// Full DCNC composition name (normally the folder name). ISDCF
        /// expects this — not the human title — as the CPL ContentTitleText.
        public let dcncName: String
        /// SMPTE 429-7 ContentKind vocabulary value ("feature", "short", …).
        public let contentKind: String?
        public let container: DCPContainer
        public let editRate: EditRate
        public let pictureURL: URL
        public let pictureUUID: UUID
        public let soundURL: URL?
        public let soundUUID: UUID?
        public let frameCount: Int
        public let issueDate: Date

        public init(folderURL: URL, contentTitle: String, dcncName: String? = nil,
                    contentKind: String? = nil,
                    container: DCPContainer, editRate: EditRate = .fps24,
                    pictureURL: URL, pictureUUID: UUID,
                    soundURL: URL?, soundUUID: UUID?,
                    frameCount: Int, issueDate: Date = Date()) {
            self.folderURL = folderURL
            self.contentTitle = contentTitle
            self.dcncName = dcncName ?? folderURL.lastPathComponent
            self.contentKind = contentKind
            self.container = container
            self.editRate = editRate
            self.pictureURL = pictureURL
            self.pictureUUID = pictureUUID
            self.soundURL = soundURL
            self.soundUUID = soundUUID
            self.frameCount = frameCount
            self.issueDate = issueDate
        }
    }

    /// One composition (one CPL / one title on the cinema server). A package
    /// holds one or more; each carries its own edit rate, container, and title.
    public struct Composition {
        public var dcncName: String
        public var contentTitle: String
        public var contentKind: String
        public var container: DCPContainer
        public var editRate: EditRate
        public var pictureURL: URL
        public var pictureUUID: UUID
        public var soundURL: URL?
        public var soundUUID: UUID?
        public var frameCount: Int
        public var cplUUID: UUID
        public var contentVersionUUID: UUID
        public var reelUUID: UUID

        public init(dcncName: String, contentTitle: String, contentKind: String,
                    container: DCPContainer, editRate: EditRate,
                    pictureURL: URL, pictureUUID: UUID,
                    soundURL: URL?, soundUUID: UUID?, frameCount: Int,
                    cplUUID: UUID = UUID(), contentVersionUUID: UUID = UUID(),
                    reelUUID: UUID = UUID()) {
            self.dcncName = dcncName
            self.contentTitle = contentTitle
            self.contentKind = contentKind
            self.container = container
            self.editRate = editRate
            self.pictureURL = pictureURL
            self.pictureUUID = pictureUUID
            self.soundURL = soundURL
            self.soundUUID = soundUUID
            self.frameCount = frameCount
            self.cplUUID = cplUUID
            self.contentVersionUUID = contentVersionUUID
            self.reelUUID = reelUUID
        }
    }

    public struct Output {
        /// First composition's CPL (convenience for the single-composition case).
        public var cplURL: URL { cplURLs[0] }
        public let cplURLs: [URL]
        public let pklURL: URL
        public let assetMapURL: URL
        public let volIndexURL: URL
        /// (filename, base64 SHA-1) as written into the PKL — reused by the
        /// QC report so nothing gets hashed twice.
        public let assetHashes: [(name: String, sha1: String)]
    }

    /// Single-composition convenience — writes one CPL plus the package
    /// wrapper. Kept for the common one-video export and existing tests.
    @discardableResult
    public static func write(_ input: Input,
                             cplUUID: UUID = UUID(),
                             pklUUID: UUID = UUID(),
                             assetMapUUID: UUID = UUID(),
                             contentVersionUUID: UUID = UUID(),
                             reelUUID: UUID = UUID()) throws -> Output {
        let contentKind = input.contentKind
            ?? (input.frameCount < 40 * 60 * input.editRate.fps ? "short" : "feature")
        let composition = Composition(
            dcncName: input.dcncName,
            contentTitle: input.contentTitle,
            contentKind: contentKind,
            container: input.container,
            editRate: input.editRate,
            pictureURL: input.pictureURL,
            pictureUUID: input.pictureUUID,
            soundURL: input.soundURL,
            soundUUID: input.soundUUID,
            frameCount: input.frameCount,
            cplUUID: cplUUID,
            contentVersionUUID: contentVersionUUID,
            reelUUID: reelUUID)
        return try writePackage(folderURL: input.folderURL, compositions: [composition],
                                issueDate: input.issueDate,
                                pklUUID: pklUUID, assetMapUUID: assetMapUUID)
    }

    /// Writes a complete DCP: one CPL per composition, then a single PKL,
    /// ASSETMAP, and VOLINDEX covering all of them. Track files must be
    /// finalized before calling (they get hashed).
    @discardableResult
    public static func writePackage(folderURL: URL, compositions: [Composition],
                                    issueDate issueDateValue: Date = Date(),
                                    pklUUID: UUID = UUID(),
                                    assetMapUUID: UUID = UUID()) throws -> Output {
        precondition(!compositions.isEmpty, "a DCP package needs at least one composition")
        let issueDate = iso8601(issueDateValue)
        // The package's overall annotation is the first composition's title.
        let packageTitle = compositions[0].contentTitle

        // --- CPLs (one per composition) ---
        var cplURLs: [URL] = []
        for composition in compositions {
            let cplURL = folderURL.appendingPathComponent("CPL_\(uuidString(composition.cplUUID)).xml")
            try write(xml: makeCPLXML(composition, issueDate: issueDate), to: cplURL)
            cplURLs.append(cplURL)
        }

        // --- PKL: all MXFs + all CPLs ---
        var pklAssetEntries: [(uuid: UUID, url: URL, type: String)] = []
        for (index, composition) in compositions.enumerated() {
            pklAssetEntries.append((composition.pictureUUID, composition.pictureURL, "application/mxf"))
            if let soundURL = composition.soundURL, let soundUUID = composition.soundUUID {
                pklAssetEntries.append((soundUUID, soundURL, "application/mxf"))
            }
            pklAssetEntries.append((composition.cplUUID, cplURLs[index], "text/xml"))
        }

        var pklAssets = ""
        var assetHashes: [(name: String, sha1: String)] = []
        for entry in pklAssetEntries {
            let size = try fileSize(entry.url)
            let hash = try sha1Base64(of: entry.url)
            assetHashes.append((entry.url.lastPathComponent, hash))
            pklAssets += """
            <Asset>
              <Id>urn:uuid:\(uuidString(entry.uuid))</Id>
              <AnnotationText>\(xmlEscape(entry.url.lastPathComponent))</AnnotationText>
              <Hash>\(hash)</Hash>
              <Size>\(size)</Size>
              <Type>\(entry.type)</Type>
              <OriginalFileName>\(xmlEscape(entry.url.lastPathComponent))</OriginalFileName>
            </Asset>

        """
        }

        let pklURL = folderURL.appendingPathComponent("PKL_\(uuidString(pklUUID)).xml")
        let pkl = """
        <?xml version="1.0" encoding="UTF-8" standalone="no"?>
        <PackingList xmlns="http://www.smpte-ra.org/schemas/429-8/2007/PKL">
          <Id>urn:uuid:\(uuidString(pklUUID))</Id>
          <AnnotationText>\(xmlEscape(packageTitle))</AnnotationText>
          <IssueDate>\(issueDate)</IssueDate>
          <Issuer>\(xmlEscape(issuer))</Issuer>
          <Creator>\(xmlEscape(creator))</Creator>
          <AssetList>
        \(indent(pklAssets, by: 4))
          </AssetList>
        </PackingList>
        """
        try write(xml: pkl, to: pklURL)

        // --- ASSETMAP: PKL first, then every CPL + MXF ---
        var mapEntries: [(uuid: UUID, url: URL, isPKL: Bool)] = [(pklUUID, pklURL, true)]
        for (index, composition) in compositions.enumerated() {
            mapEntries.append((composition.cplUUID, cplURLs[index], false))
            mapEntries.append((composition.pictureUUID, composition.pictureURL, false))
            if let soundURL = composition.soundURL, let soundUUID = composition.soundUUID {
                mapEntries.append((soundUUID, soundURL, false))
            }
        }

        var mapAssets = ""
        for entry in mapEntries {
            let size = try fileSize(entry.url)
            mapAssets += """
            <Asset>
              <Id>urn:uuid:\(uuidString(entry.uuid))</Id>
        \(entry.isPKL ? "      <PackingList>true</PackingList>\n" : "")\
              <ChunkList>
                <Chunk>
                  <Path>\(xmlEscape(entry.url.lastPathComponent))</Path>
                  <VolumeIndex>1</VolumeIndex>
                  <Offset>0</Offset>
                  <Length>\(size)</Length>
                </Chunk>
              </ChunkList>
            </Asset>

        """
        }

        let assetMapURL = folderURL.appendingPathComponent("ASSETMAP.xml")
        let assetMap = """
        <?xml version="1.0" encoding="UTF-8" standalone="no"?>
        <AssetMap xmlns="http://www.smpte-ra.org/schemas/429-9/2007/AM">
          <Id>urn:uuid:\(uuidString(assetMapUUID))</Id>
          <AnnotationText>\(xmlEscape(packageTitle))</AnnotationText>
          <Creator>\(xmlEscape(creator))</Creator>
          <VolumeCount>1</VolumeCount>
          <IssueDate>\(issueDate)</IssueDate>
          <Issuer>\(xmlEscape(issuer))</Issuer>
          <AssetList>
        \(indent(mapAssets, by: 4))
          </AssetList>
        </AssetMap>
        """
        try write(xml: assetMap, to: assetMapURL)

        // --- VOLINDEX ---
        let volIndexURL = folderURL.appendingPathComponent("VOLINDEX.xml")
        let volIndex = """
        <?xml version="1.0" encoding="UTF-8" standalone="no"?>
        <VolumeIndex xmlns="http://www.smpte-ra.org/schemas/429-9/2007/AM">
          <Index>1</Index>
        </VolumeIndex>
        """
        try write(xml: volIndex, to: volIndexURL)

        return Output(cplURLs: cplURLs, pklURL: pklURL,
                      assetMapURL: assetMapURL, volIndexURL: volIndexURL,
                      assetHashes: assetHashes)
    }

    private static func makeCPLXML(_ composition: Composition, issueDate: String) -> String {
        let editRate = composition.editRate.xmlString
        var reelAssets = """
                <MainPicture>
                  <Id>urn:uuid:\(uuidString(composition.pictureUUID))</Id>
                  <AnnotationText>\(xmlEscape(composition.pictureURL.lastPathComponent))</AnnotationText>
                  <EditRate>\(editRate)</EditRate>
                  <IntrinsicDuration>\(composition.frameCount)</IntrinsicDuration>
                  <EntryPoint>0</EntryPoint>
                  <Duration>\(composition.frameCount)</Duration>
                  <FrameRate>\(editRate)</FrameRate>
                  <ScreenAspectRatio>\(composition.container.width) \(composition.container.height)</ScreenAspectRatio>
                </MainPicture>
        """
        if let soundURL = composition.soundURL, let soundUUID = composition.soundUUID {
            reelAssets += "\n" + """
                <MainSound>
                  <Id>urn:uuid:\(uuidString(soundUUID))</Id>
                  <AnnotationText>\(xmlEscape(soundURL.lastPathComponent))</AnnotationText>
                  <EditRate>\(editRate)</EditRate>
                  <IntrinsicDuration>\(composition.frameCount)</IntrinsicDuration>
                  <EntryPoint>0</EntryPoint>
                  <Duration>\(composition.frameCount)</Duration>
                </MainSound>
        """
        }

        return """
        <?xml version="1.0" encoding="UTF-8" standalone="no"?>
        <CompositionPlaylist xmlns="http://www.smpte-ra.org/schemas/429-7/2006/CPL">
          <Id>urn:uuid:\(uuidString(composition.cplUUID))</Id>
          <AnnotationText>\(xmlEscape(composition.contentTitle))</AnnotationText>
          <IssueDate>\(issueDate)</IssueDate>
          <Issuer>\(xmlEscape(issuer))</Issuer>
          <Creator>\(xmlEscape(creator))</Creator>
          <ContentTitleText>\(xmlEscape(composition.dcncName))</ContentTitleText>
          <ContentKind>\(composition.contentKind)</ContentKind>
          <ContentVersion>
            <Id>urn:uuid:\(uuidString(composition.contentVersionUUID))</Id>
            <LabelText>\(xmlEscape(composition.dcncName))_version-1</LabelText>
          </ContentVersion>
          <RatingList/>
          <ReelList>
            <Reel>
              <Id>urn:uuid:\(uuidString(composition.reelUUID))</Id>
              <AssetList>
        \(reelAssets)
              </AssetList>
            </Reel>
          </ReelList>
        </CompositionPlaylist>
        """
    }

    /// Digital-cinema-naming-convention-style folder name, e.g.
    /// "MyFilm_SHR-1_F_XX-XX_51_2K_20260713_PRC_SMPTE_OV".
    public static func folderName(contentTitle: String, container: DCPContainer,
                                  frameCount: Int, hasAudio: Bool,
                                  options: DCNCOptions = DCNCOptions(),
                                  issueDate: Date = Date()) -> String {
        let cleanTitle = sanitizeTitleForName(contentTitle)
        let kind = options.resolvedKind(frameCount: frameCount).rawValue
        let containerCode = container == .flat ? "F" : "S"
        let audioLanguage = DCNCOptions.sanitizeCode(options.audioLanguage, fallback: "XX", maxLength: 3)
        let subtitleLanguage = DCNCOptions.sanitizeCode(options.subtitleLanguage, fallback: "XX", maxLength: 3)
        let facility = DCNCOptions.sanitizeCode(options.facility, fallback: "PRC", maxLength: 4)
        let audio = hasAudio ? "51" : "MOS"
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyyMMdd"
        formatter.timeZone = TimeZone(identifier: "UTC")
        let date = formatter.string(from: issueDate)
        return "\(cleanTitle)_\(kind)-1_\(containerCode)_\(audioLanguage)-\(subtitleLanguage)_\(audio)_2K_\(date)_\(facility)_SMPTE_OV"
    }

    static func sanitizeTitleForName(_ title: String) -> String {
        let words = title.split(whereSeparator: { !$0.isLetter && !$0.isNumber })
        let joined = words.map { word -> String in
            guard let first = word.first else { return "" }
            return first.uppercased() + word.dropFirst()
        }.joined()
        let clamped = String(joined.prefix(14))
        return clamped.isEmpty ? "Untitled" : clamped
    }

    // MARK: - Helpers

    public static func sha1Base64(of url: URL) throws -> String {
        guard let handle = try? FileHandle(forReadingFrom: url) else {
            throw ExportError.packagingFailed("cannot read \(url.lastPathComponent) for hashing")
        }
        defer { try? handle.close() }
        var hasher = Insecure.SHA1()
        while true {
            guard let chunk = try handle.read(upToCount: 4 * 1024 * 1024), !chunk.isEmpty else { break }
            hasher.update(data: chunk)
        }
        return Data(hasher.finalize()).base64EncodedString()
    }

    public static func fileSize(_ url: URL) throws -> Int64 {
        let values = try url.resourceValues(forKeys: [.fileSizeKey])
        guard let size = values.fileSize else {
            throw ExportError.packagingFailed("cannot stat \(url.lastPathComponent)")
        }
        return Int64(size)
    }

    static func uuidString(_ uuid: UUID) -> String {
        uuid.uuidString.lowercased()
    }

    static func iso8601(_ date: Date) -> String {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime]
        return formatter.string(from: date)
    }

    static func xmlEscape(_ text: String) -> String {
        text.replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&apos;")
    }

    private static func indent(_ block: String, by spaces: Int) -> String {
        let pad = String(repeating: " ", count: spaces)
        return block
            .split(separator: "\n", omittingEmptySubsequences: false)
            .map { $0.isEmpty ? "" : pad + $0 }
            .joined(separator: "\n")
            .trimmingCharacters(in: .newlines)
    }

    private static func write(xml: String, to url: URL) throws {
        do {
            try xml.write(to: url, atomically: true, encoding: .utf8)
        } catch {
            throw ExportError.packagingFailed("cannot write \(url.lastPathComponent): \(error.localizedDescription)")
        }
    }
}
