import CryptoKit
import Foundation
import TranscodeKit

/// SMPTE ST 429 packaging: CPL (429-7), PKL (429-8), ASSETMAP/VOLINDEX (429-9).
/// XML is generated by templating — the formats are small, fixed, and golden-file tested.
public enum DCPPackage {
    public static let issuer = "kennethbeckerdite"
    public static let creator = "ProRes Compressor 0.1.0"

    public struct Input {
        public let folderURL: URL
        public let contentTitle: String
        /// Full DCNC composition name (normally the folder name). ISDCF
        /// expects this — not the human title — as the CPL ContentTitleText.
        public let dcncName: String
        public let container: DCPContainer
        public let pictureURL: URL
        public let pictureUUID: UUID
        public let soundURL: URL?
        public let soundUUID: UUID?
        public let frameCount: Int
        public let issueDate: Date

        public init(folderURL: URL, contentTitle: String, dcncName: String? = nil,
                    container: DCPContainer,
                    pictureURL: URL, pictureUUID: UUID,
                    soundURL: URL?, soundUUID: UUID?,
                    frameCount: Int, issueDate: Date = Date()) {
            self.folderURL = folderURL
            self.contentTitle = contentTitle
            self.dcncName = dcncName ?? folderURL.lastPathComponent
            self.container = container
            self.pictureURL = pictureURL
            self.pictureUUID = pictureUUID
            self.soundURL = soundURL
            self.soundUUID = soundUUID
            self.frameCount = frameCount
            self.issueDate = issueDate
        }
    }

    public struct Output {
        public let cplURL: URL
        public let pklURL: URL
        public let assetMapURL: URL
        public let volIndexURL: URL
    }

    /// Writes CPL, PKL, ASSETMAP, VOLINDEX next to the track files.
    /// Track files must be finalized before calling (they get hashed).
    public static func write(_ input: Input,
                             cplUUID: UUID = UUID(),
                             pklUUID: UUID = UUID(),
                             assetMapUUID: UUID = UUID(),
                             contentVersionUUID: UUID = UUID(),
                             reelUUID: UUID = UUID()) throws -> Output {
        let title = input.contentTitle
        let issueDate = iso8601(input.issueDate)

        // --- CPL ---
        let cplName = "CPL_\(uuidString(cplUUID)).xml"
        let cplURL = input.folderURL.appendingPathComponent(cplName)
        let contentKind = input.frameCount < 40 * 60 * 24 ? "short" : "feature"

        var reelAssets = """
                <MainPicture>
                  <Id>urn:uuid:\(uuidString(input.pictureUUID))</Id>
                  <AnnotationText>\(xmlEscape(input.pictureURL.lastPathComponent))</AnnotationText>
                  <EditRate>24 1</EditRate>
                  <IntrinsicDuration>\(input.frameCount)</IntrinsicDuration>
                  <EntryPoint>0</EntryPoint>
                  <Duration>\(input.frameCount)</Duration>
                  <FrameRate>24 1</FrameRate>
                  <ScreenAspectRatio>\(input.container.width) \(input.container.height)</ScreenAspectRatio>
                </MainPicture>
        """
        if let soundURL = input.soundURL, let soundUUID = input.soundUUID {
            reelAssets += "\n" + """
                <MainSound>
                  <Id>urn:uuid:\(uuidString(soundUUID))</Id>
                  <AnnotationText>\(xmlEscape(soundURL.lastPathComponent))</AnnotationText>
                  <EditRate>24 1</EditRate>
                  <IntrinsicDuration>\(input.frameCount)</IntrinsicDuration>
                  <EntryPoint>0</EntryPoint>
                  <Duration>\(input.frameCount)</Duration>
                </MainSound>
        """
        }

        let cpl = """
        <?xml version="1.0" encoding="UTF-8" standalone="no"?>
        <CompositionPlaylist xmlns="http://www.smpte-ra.org/schemas/429-7/2006/CPL">
          <Id>urn:uuid:\(uuidString(cplUUID))</Id>
          <AnnotationText>\(xmlEscape(title))</AnnotationText>
          <IssueDate>\(issueDate)</IssueDate>
          <Issuer>\(xmlEscape(issuer))</Issuer>
          <Creator>\(xmlEscape(creator))</Creator>
          <ContentTitleText>\(xmlEscape(input.dcncName))</ContentTitleText>
          <ContentKind>\(contentKind)</ContentKind>
          <ContentVersion>
            <Id>urn:uuid:\(uuidString(contentVersionUUID))</Id>
            <LabelText>\(xmlEscape(input.dcncName))_version-1</LabelText>
          </ContentVersion>
          <RatingList/>
          <ReelList>
            <Reel>
              <Id>urn:uuid:\(uuidString(reelUUID))</Id>
              <AssetList>
        \(reelAssets)
              </AssetList>
            </Reel>
          </ReelList>
        </CompositionPlaylist>
        """
        try write(xml: cpl, to: cplURL)

        // --- PKL (hashes cover the finalized MXFs and the CPL just written) ---
        let pklName = "PKL_\(uuidString(pklUUID)).xml"
        let pklURL = input.folderURL.appendingPathComponent(pklName)

        var pklAssetEntries: [(uuid: UUID, url: URL, type: String)] = [
            (input.pictureUUID, input.pictureURL, "application/mxf"),
        ]
        if let soundURL = input.soundURL, let soundUUID = input.soundUUID {
            pklAssetEntries.append((soundUUID, soundURL, "application/mxf"))
        }
        pklAssetEntries.append((cplUUID, cplURL, "text/xml"))

        var pklAssets = ""
        for entry in pklAssetEntries {
            let size = try fileSize(entry.url)
            let hash = try sha1Base64(of: entry.url)
            pklAssets += """
            <Asset>
              <Id>urn:uuid:\(uuidString(entry.uuid))</Id>
              <AnnotationText>\(xmlEscape(entry.url.lastPathComponent))</AnnotationText>
              <Hash>\(hash)</Hash>
              <Size>\(size)</Size>
              <Type>\(entry.type)</Type>
              <OriginalFileName>\(xmlEscape(entry.url.lastPathComponent))</OriginalFileName>
            </Asset>

        """
        }

        let pkl = """
        <?xml version="1.0" encoding="UTF-8" standalone="no"?>
        <PackingList xmlns="http://www.smpte-ra.org/schemas/429-8/2007/PKL">
          <Id>urn:uuid:\(uuidString(pklUUID))</Id>
          <AnnotationText>\(xmlEscape(title))</AnnotationText>
          <IssueDate>\(issueDate)</IssueDate>
          <Issuer>\(xmlEscape(issuer))</Issuer>
          <Creator>\(xmlEscape(creator))</Creator>
          <AssetList>
        \(indent(pklAssets, by: 4))
          </AssetList>
        </PackingList>
        """
        try write(xml: pkl, to: pklURL)

        // --- ASSETMAP ---
        let assetMapURL = input.folderURL.appendingPathComponent("ASSETMAP.xml")

        var mapEntries: [(uuid: UUID, url: URL, isPKL: Bool)] = [
            (pklUUID, pklURL, true),
            (cplUUID, cplURL, false),
            (input.pictureUUID, input.pictureURL, false),
        ]
        if let soundURL = input.soundURL, let soundUUID = input.soundUUID {
            mapEntries.append((soundUUID, soundURL, false))
        }

        var mapAssets = ""
        for entry in mapEntries {
            let size = try fileSize(entry.url)
            mapAssets += """
            <Asset>
              <Id>urn:uuid:\(uuidString(entry.uuid))</Id>
        \(entry.isPKL ? "      <PackingList>true</PackingList>\n" : "")\
              <ChunkList>
                <Chunk>
                  <Path>\(xmlEscape(entry.url.lastPathComponent))</Path>
                  <VolumeIndex>1</VolumeIndex>
                  <Offset>0</Offset>
                  <Length>\(size)</Length>
                </Chunk>
              </ChunkList>
            </Asset>

        """
        }

        let assetMap = """
        <?xml version="1.0" encoding="UTF-8" standalone="no"?>
        <AssetMap xmlns="http://www.smpte-ra.org/schemas/429-9/2007/AM">
          <Id>urn:uuid:\(uuidString(assetMapUUID))</Id>
          <AnnotationText>\(xmlEscape(title))</AnnotationText>
          <Creator>\(xmlEscape(creator))</Creator>
          <VolumeCount>1</VolumeCount>
          <IssueDate>\(issueDate)</IssueDate>
          <Issuer>\(xmlEscape(issuer))</Issuer>
          <AssetList>
        \(indent(mapAssets, by: 4))
          </AssetList>
        </AssetMap>
        """
        try write(xml: assetMap, to: assetMapURL)

        // --- VOLINDEX ---
        let volIndexURL = input.folderURL.appendingPathComponent("VOLINDEX.xml")
        let volIndex = """
        <?xml version="1.0" encoding="UTF-8" standalone="no"?>
        <VolumeIndex xmlns="http://www.smpte-ra.org/schemas/429-9/2007/AM">
          <Index>1</Index>
        </VolumeIndex>
        """
        try write(xml: volIndex, to: volIndexURL)

        return Output(cplURL: cplURL, pklURL: pklURL,
                      assetMapURL: assetMapURL, volIndexURL: volIndexURL)
    }

    /// Digital-cinema-naming-convention-style folder name, e.g.
    /// "MyFilm_SHR-1_F_XX-XX_51_2K_20260713_PRC_SMPTE_OV".
    public static func folderName(contentTitle: String, container: DCPContainer,
                                  frameCount: Int, hasAudio: Bool, issueDate: Date = Date()) -> String {
        let cleanTitle = sanitizeTitleForName(contentTitle)
        let kind = frameCount < 40 * 60 * 24 ? "SHR" : "FTR"
        let containerCode = container == .flat ? "F" : "S"
        let audio = hasAudio ? "51" : "MOS"
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyyMMdd"
        formatter.timeZone = TimeZone(identifier: "UTC")
        let date = formatter.string(from: issueDate)
        return "\(cleanTitle)_\(kind)-1_\(containerCode)_XX-XX_\(audio)_2K_\(date)_PRC_SMPTE_OV"
    }

    static func sanitizeTitleForName(_ title: String) -> String {
        let words = title.split(whereSeparator: { !$0.isLetter && !$0.isNumber })
        let joined = words.map { word -> String in
            guard let first = word.first else { return "" }
            return first.uppercased() + word.dropFirst()
        }.joined()
        let clamped = String(joined.prefix(14))
        return clamped.isEmpty ? "Untitled" : clamped
    }

    // MARK: - Helpers

    public static func sha1Base64(of url: URL) throws -> String {
        guard let handle = try? FileHandle(forReadingFrom: url) else {
            throw ExportError.packagingFailed("cannot read \(url.lastPathComponent) for hashing")
        }
        defer { try? handle.close() }
        var hasher = Insecure.SHA1()
        while true {
            guard let chunk = try handle.read(upToCount: 4 * 1024 * 1024), !chunk.isEmpty else { break }
            hasher.update(data: chunk)
        }
        return Data(hasher.finalize()).base64EncodedString()
    }

    public static func fileSize(_ url: URL) throws -> Int64 {
        let values = try url.resourceValues(forKeys: [.fileSizeKey])
        guard let size = values.fileSize else {
            throw ExportError.packagingFailed("cannot stat \(url.lastPathComponent)")
        }
        return Int64(size)
    }

    static func uuidString(_ uuid: UUID) -> String {
        uuid.uuidString.lowercased()
    }

    static func iso8601(_ date: Date) -> String {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime]
        return formatter.string(from: date)
    }

    static func xmlEscape(_ text: String) -> String {
        text.replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&apos;")
    }

    private static func indent(_ block: String, by spaces: Int) -> String {
        let pad = String(repeating: " ", count: spaces)
        return block
            .split(separator: "\n", omittingEmptySubsequences: false)
            .map { $0.isEmpty ? "" : pad + $0 }
            .joined(separator: "\n")
            .trimmingCharacters(in: .newlines)
    }

    private static func write(xml: String, to url: URL) throws {
        do {
            try xml.write(to: url, atomically: true, encoding: .utf8)
        } catch {
            throw ExportError.packagingFailed("cannot write \(url.lastPathComponent): \(error.localizedDescription)")
        }
    }
}
